### ISSUE TITLE
Make `DeepONet` and `FourierNeuralOperator` into structs

### ISSUE THREAD

**Issue by KirillZubov** [LuxDL/NeuralOperators.jl#16]
```julia
deeponet = NeuralOperators.DeepONet(
    Chain(
        Dense(1 => 10, Lux.tanh_fast), Dense(10 => 10, Lux.tanh_fast), Dense(10 => 10)),
    Chain(Dense(1 => 10, Lux.tanh_fast), Dense(10 => 10, Lux.tanh_fast),
        Dense(10 => 10, Lux.tanh_fast)))
julia> deeponet.name ==nothing 
true
```
it guess it should be something like  deeponet.name  == "DeepONet"

**Comment by KirillZubov** [comment]
@avik-pal  is there  another easy way to find out the type of Lux.NeuralOperator? is it DeepONet or FourierNeuralOperator and etc?

**Comment by avik-pal** [comment]
No don't dispatch on `name`, `name` is used for pretty printing. Use `CompactLuxLayer{:DeepONet}`.

**Comment by KirillZubov** [comment]
@avik-pal ok, how identify type of FourierNeuralOperator?

**Comment by avik-pal** [comment]
FNO just returns a Chain. We could modify it to return a layer that can be dispatched on.

**Comment by avik-pal** [comment]
@ayushinav can you get this done?

**Comment by ayushinav** [comment]
We can probably make a `CompactLayer` for FNOs too and other architectures in future, otherwise the structs would only contain the chain of the operator. Making a struct for different parameters of each operator sort of defeats the purpose of how useful `CompactLayer`s are.
For now, I'm inclined towards creating a struct with only the chain as its parameter.
